@startuml name diagrama1
left to right direction
actor "Parceiro" as Parceiro
actor "Doador" as Doador
actor "ONG Parceira" as ONG
actor "Administrador da ONG" as Admin
rectangle sistema {
    Parceiro -- (Logar)
    Parceiro -- (Preencher Formulário de Cadastro)
    (Preencher Formulário de Cadastro) .> (Validar Cadastro) : include
    (Validar Cadastro) -- Admin

    Parceiro <- Doador
    Parceiro <- ONG

    ONG -- (Solicitar Doação)
    (Solicitar Doação) .> (Preencher Formulário "Quero receber doações") : include

    Doador - (Postar Doação)
    (Verificar doação) -- Admin
    (Aceitar Doação) -- Admin
    (Verificar doação) <. (Aceitar Doação) : extends
    (Aceitar Doação) .> (Postar no Estoque) : include
    (Verificar doação) <. (Postar Doação) : include
    (Disponibilizar pra ONGs Parceiras) .> (Verificar doação) : extends
    ONG - (Aceitar doação)
    (Aceitar doação) .> (Disponibilizar pra ONGs Parceiras) : extends

    Admin - (Acessar estoque)
    (Acessar estoque) .> (Filtrar Informações) : extends

    Admin - (Criar Nova Campanha)
    (Criar Nova Campanha) .> (Postar Campanha) : extends
    (Visualizar Campanhas) -- Admin
    (Postar Campanha) .> (Notificar Parceiro) : extends

    Admin - (Acessar Ranking de Doadores)
    (Acessar Ranking de Doadores) .> (Filtrar Ranking) : extends

    (Acessar ONGs Cadastradas) -- Admin
    (Acessar ONGs Cadastradas) .> (Ver informações) : extends

    Doador -- (Ver Doações Anteriores)
}

@enduml