@startuml
left to right direction

actor Usuario as Usuario
actor ParceiroONG as "Parceiro da ONG"
actor ONG as ONG

Usuario <|-- ParceiroONG
Usuario <|-- ONG

rectangle "Sistema de Doações" {
    Usuario -- (RF002 - Login de usuário)
    ParceiroONG -- (RF001 - Cadastro de parceiros)
    ONG -- (RF004 - Cadastro de campanhas)
    ONG -- (RF005 - Visualização de campanhas disponíveis pela ONG)
    ONG -- (RF006 - Visualização de tabela de doações)
    ParceiroONG -- (RF007 - Visualização de campanhas disponíveis pelo parceiro da ONG)
    ParceiroONG -- (RF008 - Envio de formulário para doação)
    ParceiroONG -- (RF009 - Envio de formulário para recebimento de doação)
    ParceiroONG -- (RF010 - Acompanhamento de doações registradas)
    ParceiroONG -- (RF011 - Acompanhamento de solicitações registradas)
    ONG -- (RF012 - Gerenciamento de entrada de doações)
    ONG -- (RF013 - Gerenciamento de saída de doações)
    ParceiroONG -- (RF014 - Notificação de parceiros)
    ONG -- (RF015 - Geração de relatórios)
    ONG -- (RF003 - Visualização de ranking de doadores)
}
@enduml
